<?php

/**
 * Resume builder intake / screening questions — modelled on onboarding flows from
 * JobCopilot (https://jobcopilot.com) and ResumeBuilder.com (https://app.resumebuilder.com).
 * No public API exists on those platforms; this catalog mirrors their publicly described prompts.
 */
return [
    'sources' => [
        [
            'id' => 'jobcopilot',
            'name' => 'JobCopilot',
            'url' => 'https://jobcopilot.com',
            'description' => 'Job search filters, work authorization, and auto-apply preferences.',
        ],
        [
            'id' => 'resumebuilder',
            'name' => 'ResumeBuilder.com',
            'url' => 'https://app.resumebuilder.com',
            'description' => 'Career level, target role, and resume tailoring intake.',
        ],
    ],
    'questions' => [
        // —— ResumeBuilder.com style intake ——
        [
            'id' => 'target_job_title',
            'label' => 'What job title are you targeting?',
            'help_text' => 'Choose from common roles or enter your own title.',
            'type' => 'job_title',
            'placeholder' => 'Your target role',
            'required' => true,
            'source' => 'resumebuilder',
            'category' => 'career_goal',
        ],
        [
            'id' => 'career_level',
            'label' => 'What is your career level?',
            'help_text' => 'ResumeBuilder uses this to suggest the right template and content tone.',
            'type' => 'single_choice',
            'options' => [
                'Student / Intern',
                'Entry level (0–2 years)',
                'Mid-career (3–7 years)',
                'Senior (8–14 years)',
                'Executive / Director+',
            ],
            'required' => true,
            'source' => 'resumebuilder',
            'category' => 'experience',
        ],
        [
            'id' => 'industry',
            'label' => 'Which industry best matches your target role?',
            'type' => 'single_choice',
            'options' => [
                'Technology & IT',
                'Finance & Accounting',
                'Sales & Marketing',
                'Healthcare',
                'Engineering & Construction',
                'Hospitality & Retail',
                'Education',
                'Government & Public Sector',
                'Other',
            ],
            'required' => true,
            'source' => 'resumebuilder',
            'category' => 'career_goal',
        ],
        [
            'id' => 'highest_education',
            'label' => 'What is your highest level of education?',
            'type' => 'single_choice',
            'options' => [
                'High school',
                'Diploma / Certificate',
                "Bachelor's degree",
                "Master's degree",
                'Doctorate / PhD',
                'Prefer not to say',
            ],
            'required' => true,
            'source' => 'resumebuilder',
            'category' => 'education',
        ],
        [
            'id' => 'employment_status',
            'label' => 'What is your current employment status?',
            'type' => 'single_choice',
            'options' => [
                'Employed — actively looking',
                'Employed — open to offers',
                'Unemployed — actively looking',
                'Student / recent graduate',
                'Freelancer / contractor',
            ],
            'required' => true,
            'source' => 'resumebuilder',
            'category' => 'availability',
        ],
        [
            'id' => 'target_start_date',
            'label' => 'When could you start a new role?',
            'type' => 'single_choice',
            'options' => [
                'Immediately',
                'Within 2 weeks',
                'Within 1 month',
                'Within 2–3 months',
                'Flexible',
            ],
            'required' => false,
            'source' => 'resumebuilder',
            'category' => 'availability',
        ],

        // —— JobCopilot style intake ——
        [
            'id' => 'job_search_status',
            'label' => 'How actively are you job searching?',
            'help_text' => 'JobCopilot uses this to prioritize applications and outreach.',
            'type' => 'single_choice',
            'options' => [
                'Very active — applying daily',
                'Active — applying several times per week',
                'Passive — open to the right opportunity',
                'Exploring options only',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'job_search',
        ],
        [
            'id' => 'preferred_locations',
            'label' => 'Which locations are you open to?',
            'help_text' => 'Select all that apply — JobCopilot filters jobs by location preferences.',
            'type' => 'multi_choice',
            'options' => [
                'Dubai',
                'Abu Dhabi',
                'Sharjah',
                'Other UAE emirates',
                'Remote — UAE based',
                'Remote — international',
                'Willing to relocate within GCC',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'job_search',
        ],
        [
            'id' => 'work_arrangement',
            'label' => 'Preferred work arrangement',
            'type' => 'single_choice',
            'options' => [
                'On-site only',
                'Hybrid',
                'Remote only',
                'No preference',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'job_search',
        ],
        [
            'id' => 'years_experience',
            'label' => 'How many years of relevant experience do you have?',
            'type' => 'single_choice',
            'options' => [
                'Less than 1 year',
                '1–2 years',
                '3–5 years',
                '6–8 years',
                '9–12 years',
                '13+ years',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'experience',
        ],
        [
            'id' => 'work_authorization',
            'label' => 'Are you legally authorized to work in the UAE?',
            'type' => 'single_choice',
            'options' => ['Yes', 'No', 'Not sure'],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'eligibility',
        ],
        [
            'id' => 'visa_sponsorship',
            'label' => 'Do you require visa sponsorship?',
            'type' => 'single_choice',
            'options' => [
                'No — valid UAE visa / passport',
                'Yes — require employer sponsorship',
                'Transferable visa with NOC',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'eligibility',
        ],
        [
            'id' => 'expected_salary',
            'label' => 'Expected monthly salary range (AED)',
            'help_text' => 'Optional — helps tailor applications; you can leave blank.',
            'type' => 'single_choice',
            'options' => [
                'Prefer not to say',
                'Below AED 5,000',
                'AED 5,000 – 10,000',
                'AED 10,000 – 20,000',
                'AED 20,000 – 35,000',
                'AED 35,000+',
            ],
            'required' => false,
            'source' => 'jobcopilot',
            'category' => 'compensation',
        ],
        [
            'id' => 'notice_period',
            'label' => 'What is your notice period?',
            'type' => 'single_choice',
            'options' => [
                'Available immediately',
                '1–2 weeks',
                '1 month',
                '2–3 months',
                'More than 3 months',
            ],
            'required' => true,
            'source' => 'jobcopilot',
            'category' => 'availability',
        ],
        [
            'id' => 'willing_to_relocate',
            'label' => 'Are you willing to relocate within the UAE for the right role?',
            'type' => 'single_choice',
            'options' => ['Yes', 'No', 'Depends on the offer'],
            'required' => false,
            'source' => 'jobcopilot',
            'category' => 'job_search',
        ],
    ],
];
