<?php

return [
    'job_title' => [
        'Software Engineer', 'Senior Software Engineer', 'Full Stack Developer',
        'Frontend Developer', 'Backend Developer', 'DevOps Engineer', 'Data Analyst',
        'Data Scientist', 'Product Manager', 'Project Manager', 'Product Designer',
        'UX Designer', 'UI Designer', 'Graphic Designer', 'Marketing Manager',
        'Digital Marketing Specialist', 'Sales Executive', 'Account Manager',
        'Business Development Manager', 'Customer Service Representative',
        'Customer Success Manager', 'Human Resources Manager', 'HR Coordinator',
        'Recruiter', 'Talent Acquisition Specialist', 'Administrative Assistant',
        'Executive Assistant', 'Office Manager', 'Accountant', 'Financial Analyst',
        'Auditor', 'Chartered Accountant', 'Civil Engineer', 'Mechanical Engineer',
        'Electrical Engineer', 'Architect', 'Quantity Surveyor', 'Property Consultant',
        'Real Estate Agent', 'Real Estate Broker', 'Nurse', 'Registered Nurse',
        'Medical Assistant', 'Pharmacist', 'Doctor', 'General Practitioner', 'Teacher',
        'Primary School Teacher', 'Teaching Assistant', 'Operations Manager',
        'Supply Chain Manager', 'Logistics Coordinator', 'Warehouse Supervisor', 'Chef',
        'Sous Chef', 'Restaurant Manager', 'Hotel Manager', 'Front Office Manager',
        'Flight Attendant', 'Pilot', 'Legal Counsel', 'Paralegal', 'Compliance Officer',
        'Bank Teller', 'Relationship Manager', 'Investment Analyst', 'Content Writer',
        'Copywriter', 'Social Media Manager', 'Public Relations Officer', 'Photographer',
        'Videographer', 'Personal Trainer', 'Fitness Instructor', 'Driver',
        'Delivery Driver', 'Security Guard', 'Facilities Manager', 'IT Support Specialist',
        'Network Engineer', 'Cybersecurity Analyst', 'Cloud Engineer',
        'Machine Learning Engineer', 'Business Analyst', 'Consultant',
        'Management Consultant', 'Intern', 'Graduate Trainee',
    ],
    'degree' => [
        'High School Diploma', 'Secondary School Certificate', 'Associate Degree',
        'Foundation Year', 'Bachelor of Arts (BA)', 'Bachelor of Science (BSc)',
        'Bachelor of Business Administration (BBA)', 'Bachelor of Engineering (BEng)',
        'Bachelor of Commerce (BCom)', 'Bachelor of Computer Science (BCS)',
        'Bachelor of Architecture (BArch)', 'Bachelor of Laws (LLB)',
        'Bachelor of Education (BEd)', 'Bachelor of Fine Arts (BFA)', 'Master of Arts (MA)',
        'Master of Science (MSc)', 'Master of Business Administration (MBA)',
        'Master of Engineering (MEng)', 'Master of Laws (LLM)',
        'Master of Public Health (MPH)', 'Master of Education (MEd)',
        'Master of Computer Science (MCS)', 'Doctor of Philosophy (PhD)',
        'Doctor of Medicine (MD)', 'Doctor of Business Administration (DBA)',
        'Diploma in Nursing', 'Diploma in Hospitality Management',
        'Diploma in Information Technology', 'Professional Certificate',
        'Postgraduate Diploma', 'Higher National Diploma (HND)',
        'International Baccalaureate (IB)', 'A-Levels', 'GCSE', 'Currently pursuing degree',
    ],
    'school' => [
        'American University of Sharjah', 'American University in Dubai',
        'United Arab Emirates University', 'Zayed University', 'Higher Colleges of Technology',
        'University of Dubai', 'Heriot-Watt University Dubai', 'Middlesex University Dubai',
        'University of Wollongong in Dubai', 'Manipal Academy of Higher Education Dubai',
        'BITS Pilani Dubai', 'Amity University Dubai', 'Canadian University Dubai',
        'Murdoch University Dubai', 'University of Birmingham Dubai',
        'University of Manchester Dubai', 'Rochester Institute of Technology Dubai',
        'Emirates Aviation University', 'Mohammed Bin Rashid University', 'Khalifa University',
        'New York University Abu Dhabi', 'Sorbonne University Abu Dhabi',
        'Paris-Sorbonne University Abu Dhabi', 'Abu Dhabi University', 'Al Ain University',
        'Ajman University', 'University of Sharjah', 'Sharjah Women\'s College', 'Dubai College',
        'GEMS Wellington Academy', 'Indian High School Dubai', 'Delhi Private School Dubai',
        'The British School Al Khubairat', 'Repton School Dubai', 'London Business School',
        'Imperial College London', 'University of Oxford', 'University of Cambridge',
        'Harvard University', 'Stanford University', 'MIT', 'National University of Singapore',
        'University of Toronto', 'University of Melbourne', 'University of Sydney',
        'Indian Institute of Technology', 'University of Mumbai', 'University of Delhi',
        'Cairo University', 'American University of Beirut', 'King Saud University',
        'Online / Distance Learning',
    ],
    'language' => [
        'English', 'Arabic', 'Hindi', 'Urdu', 'Malayalam', 'Tamil', 'Telugu', 'Bengali',
        'Tagalog', 'Filipino', 'French', 'German', 'Spanish', 'Italian', 'Portuguese',
        'Russian', 'Chinese (Mandarin)', 'Cantonese', 'Japanese', 'Korean', 'Turkish',
        'Persian (Farsi)', 'Pashto', 'Punjabi', 'Gujarati', 'Marathi', 'Nepali', 'Sinhala',
        'Indonesian', 'Malay', 'Thai', 'Vietnamese', 'Swahili', 'Amharic', 'Greek', 'Dutch',
        'Polish', 'Romanian', 'Ukrainian', 'Serbian', 'Hebrew', 'Sign Language',
    ],
    'language_level' => [
        'Native', 'Fluent', 'Professional working proficiency', 'Full professional proficiency',
        'Conversational', 'Intermediate', 'Basic', 'Elementary', 'Limited working proficiency',
        'Bilingual', 'Mother tongue',
    ],
];
