import type { RoommateProfile } from "./types";
import { DEFAULT_DEALBREAKER_KEYS } from "./config";

const u = (n: string) =>
  `https://images.unsplash.com/${n}?auto=format&fit=crop&w=400&q=80`;

function candidate(
  profile: Omit<RoommateProfile, "lookingFor"> & { roommatePreference?: string }
): RoommateProfile {
  const { roommatePreference = "Any", ...rest } = profile;
  return {
    ...rest,
    lookingFor: {
      gender_preference: roommatePreference,
    },
  };
}

/**
 * Demo candidate roommate profiles. Each one is intentionally diverse
 * so the engine has a meaningful spread to rank.
 */
export const mockCandidates: RoommateProfile[] = [
  candidate({
    userId: "rm-1",
    name: "Aisha Al Marri",
    avatar: u("photo-1494790108377-be9c29b29330"),
    gender: "Female",
    age: 28,
    occupation: "Marketing Lead at Careem",
    bio: "Foodie, gym in the mornings, quiet Sundays.",
    monthlyBudgetAed: 3200,
    moveInDate: "2026-06-01",
    leaseDuration: "12 months",
    listingId: "L-1024",
    roommatePreference: "Female",
    preferences: {
      preferred_locations: [{ emirate: "Dubai", area: "Dubai Marina" }],
      smoking: "No smoking",
      pets: "Cats OK",
      cleanliness: 5,
      noise_tolerance: 2,
      social_level: 3,
      sleep_schedule: "Standard (10pm – 1am)",
      work_from_home: 2,
      relationship_status: "Single",
      guests: "Sometimes",
      alcohol: "Occasionally",
      diet: "Vegetarian",
      age_range: [25, 35],
      languages: ["English", "Arabic"],
      ethnicity: "Arab / Middle Eastern",
      occupation_type: "Working professional",
      interests: ["Gym & fitness", "Cooking", "Travel", "Reading"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-2",
    name: "Rohan Mehta",
    avatar: u("photo-1500648767791-00dcc994a43e"),
    gender: "Male",
    age: 31,
    occupation: "Backend Engineer at Tabby",
    bio: "Code, coffee, climbing. Mostly home on Sundays.",
    monthlyBudgetAed: 2800,
    moveInDate: "2026-05-15",
    leaseDuration: "6 months",
    roommatePreference: "Any",
    preferences: {
      preferred_locations: [{ emirate: "Dubai", area: "Jumeirah Lake Towers" }],
      smoking: "Outdoors only",
      pets: "Any pets",
      cleanliness: 4,
      noise_tolerance: 3,
      social_level: 2,
      sleep_schedule: "Night owl (after 1am)",
      work_from_home: 4,
      relationship_status: "In a relationship",
      guests: "Rarely",
      alcohol: "Occasionally",
      diet: "No restrictions",
      age_range: [25, 38],
      languages: ["English", "Hindi"],
      ethnicity: "South Asian",
      occupation_type: "Working professional",
      interests: ["Tech / startups", "Outdoors / hiking", "Gaming", "Travel"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-3",
    name: "Sofia Rossi",
    avatar: u("photo-1438761681033-6461ffad8d80"),
    gender: "Female",
    age: 26,
    occupation: "Talent Partner at Tabby",
    bio: "Yoga, Sunday brunches, and the occasional house party.",
    monthlyBudgetAed: 3000,
    moveInDate: "2026-06-15",
    leaseDuration: "6 months",
    roommatePreference: "Female",
    preferences: {
      preferred_locations: [{ emirate: "Dubai", area: "Business Bay" }],
      smoking: "No smoking",
      pets: "Cats OK",
      cleanliness: 4,
      noise_tolerance: 3,
      social_level: 4,
      sleep_schedule: "Standard (10pm – 1am)",
      work_from_home: 3,
      relationship_status: "Single",
      guests: "Parties OK",
      alcohol: "Often",
      diet: "Vegetarian",
      age_range: [24, 32],
      languages: ["English", "French"],
      ethnicity: "European",
      occupation_type: "Working professional",
      interests: ["Yoga / meditation", "Travel", "Live music", "Cooking", "Art & design"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-4",
    name: "Khalid Bin Saeed",
    avatar: u("photo-1472099645785-5658abf4ff4e"),
    gender: "Male",
    age: 33,
    occupation: "Property Broker",
    bio: "Family-first, prayer times respected, very tidy.",
    monthlyBudgetAed: 4000,
    moveInDate: "2026-07-01",
    leaseDuration: "12 months",
    roommatePreference: "Family",
    preferences: {
      preferred_locations: [{ emirate: "Abu Dhabi", area: "Al Reem Island" }],
      smoking: "No smoking",
      pets: "No pets",
      cleanliness: 5,
      noise_tolerance: 1,
      social_level: 1,
      sleep_schedule: "Early bird (≤ 10pm)",
      work_from_home: 1,
      relationship_status: "Married",
      guests: "No overnight guests",
      alcohol: "Never",
      diet: "Halal only",
      age_range: [28, 45],
      languages: ["Arabic", "English", "Urdu"],
      ethnicity: "Arab / Middle Eastern",
      occupation_type: "Business owner",
      interests: ["Reading", "Travel"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-5",
    name: "Daniel Kim",
    avatar: u("photo-1507003211169-0a1dd7228f2d"),
    gender: "Male",
    age: 24,
    occupation: "Software Engineer Intern",
    bio: "Gamer, takeaway king, occasional fitness wave.",
    monthlyBudgetAed: 2200,
    moveInDate: "2026-05-20",
    roommatePreference: "Any",
    preferences: {
      preferred_locations: [{ emirate: "Sharjah", area: "Al Nahda" }],
      smoking: "No smoking",
      pets: "Dogs OK",
      cleanliness: 3,
      noise_tolerance: 4,
      social_level: 3,
      sleep_schedule: "Night owl (after 1am)",
      work_from_home: 3,
      relationship_status: "Single",
      guests: "Sometimes",
      alcohol: "Occasionally",
      diet: "No restrictions",
      age_range: [21, 30],
      languages: ["English", "Chinese"],
      ethnicity: "East Asian",
      occupation_type: "Student",
      interests: ["Gaming", "Tech / startups", "Movies & TV", "Sports"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-6",
    name: "Maria Lopez",
    avatar: u("photo-1534528741775-53994a69daeb"),
    gender: "Female",
    age: 30,
    occupation: "Designer at Property Finder",
    bio: "Plants, books, soft music. Mostly indoor.",
    monthlyBudgetAed: 3400,
    moveInDate: "2026-06-01",
    leaseDuration: "Flexible",
    roommatePreference: "Female",
    preferences: {
      preferred_locations: [{ emirate: "Dubai", area: "Downtown Dubai" }],
      smoking: "No smoking",
      pets: "Any pets",
      cleanliness: 5,
      noise_tolerance: 2,
      social_level: 2,
      sleep_schedule: "Standard (10pm – 1am)",
      work_from_home: 5,
      relationship_status: "In a relationship",
      guests: "Rarely",
      alcohol: "Occasionally",
      diet: "Vegan",
      age_range: [25, 35],
      languages: ["English", "Tagalog"],
      ethnicity: "Southeast Asian",
      occupation_type: "Working professional",
      interests: ["Reading", "Art & design", "Yoga / meditation", "Photography"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-7",
    name: "Yusuf Hassan",
    avatar: u("photo-1463453091185-61582044d556"),
    gender: "Male",
    age: 35,
    occupation: "Freelance Photographer",
    bio: "Travel often, light sleeper, love a good kitchen.",
    monthlyBudgetAed: 3100,
    moveInDate: "2026-05-10",
    leaseDuration: "3 months",
    roommatePreference: "Male",
    preferences: {
      preferred_locations: [{ emirate: "Abu Dhabi", area: "Al Reem Island" }],
      smoking: "Outdoors only",
      pets: "Cats OK",
      cleanliness: 4,
      noise_tolerance: 2,
      social_level: 3,
      sleep_schedule: "Early bird (≤ 10pm)",
      work_from_home: 4,
      relationship_status: "Engaged",
      guests: "Sometimes",
      alcohol: "Never",
      diet: "Halal only",
      age_range: [28, 40],
      languages: ["Arabic", "English"],
      occupation_type: "Freelancer",
      interests: ["Photography", "Travel", "Cooking", "Outdoors / hiking"],
    },
    isDiscoverable: true,
  }),
  candidate({
    userId: "rm-test-layla",
    name: "Layla Khaleej",
    avatar: u("photo-1544005313-94ddf0286df2"),
    gender: "Female",
    age: 27,
    occupation: "Product Designer at Noon",
    bio: "Demo profile — ~90% lifestyle match. Prefers female roommates only.",
    monthlyBudgetAed: 3500,
    moveInDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
    leaseDuration: "6 months",
    currentNeighborhood: { emirate: "Dubai", area: "Dubai Marina" },
    previousNeighborhoods: [{ emirate: "Abu Dhabi", area: "Al Reem Island" }],
    currentBuilding: "Marina Gate 1",
    previousBuildings: ["Sky View Tower"],
    roommatePreference: "Female",
    preferences: {
      preferred_locations: [{ emirate: "Dubai", area: "Dubai Marina" }],
      smoking: "No smoking",
      pets: "Cats OK",
      cleanliness: 4,
      noise_tolerance: 3,
      social_level: 3,
      sleep_schedule: "Standard (10pm – 1am)",
      work_from_home: 3,
      relationship_status: "Single",
      guests: "Sometimes",
      alcohol: "Occasionally",
      diet: "Vegetarian",
      age_range: [24, 34],
      languages: ["English"],
      ethnicity: "Arab / Middle Eastern",
      occupation_type: "Working professional",
      interests: ["Cooking", "Travel", "Reading", "Yoga / meditation"],
    },
    isDiscoverable: true,
  }),
];

/** A default seeker profile so the demo Match page works without onboarding first. */
export const demoSeeker: RoommateProfile = {
  userId: "seeker-demo",
  name: "You",
  gender: "Female",
  age: 27,
  occupation: "Product Designer",
  monthlyBudgetAed: 3500,
  moveInDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
  leaseDuration: "6 months",
  currentNeighborhood: { emirate: "Dubai", area: "Jumeirah Lake Towers" },
  previousNeighborhoods: [
    { emirate: "Dubai", area: "Bur Dubai" },
    { emirate: "Sharjah", area: "Al Nahda" },
  ],
  currentBuilding: "Goldcrest Executive",
  previousBuildings: ["Princess Tower", "Lake Terrace"],
  dealbreakers: [...DEFAULT_DEALBREAKER_KEYS],
  isDiscoverable: false,
  preferences: {
    preferred_locations: [{ emirate: "Dubai", area: "Dubai Marina" }],
    smoking: "No smoking",
    pets: "Cats OK",
    cleanliness: 4,
    noise_tolerance: 3,
    social_level: 3,
    sleep_schedule: "Standard (10pm – 1am)",
    work_from_home: 3,
    relationship_status: "Single",
    guests: "Sometimes",
    alcohol: "Occasionally",
    diet: "Vegetarian",
    languages: ["English"],
    occupation_type: "Working professional",
    interests: ["Cooking", "Travel", "Reading", "Yoga / meditation"],
  },
  lookingFor: {
    gender_preference: "Any",
    preferred_locations: [{ emirate: "Dubai", area: "Dubai Marina" }],
    smoking: "No smoking",
    pets: "Cats OK",
    cleanliness: 4,
    noise_tolerance: 3,
    social_level: 3,
    sleep_schedule: "Standard (10pm – 1am)",
    work_from_home: 3,
    guests: "Sometimes",
    alcohol: "Occasionally",
    diet: "Vegetarian",
    age_range: [24, 34],
    languages: ["English"],
    occupation_type: "Working professional",
    interests: ["Cooking", "Travel", "Reading", "Yoga / meditation"],
  },
};

/** Male seeker demo — use `/match/seeker?demo=male-seeker` to test gender filtering. */
export const demoMaleSeeker: RoommateProfile = {
  ...demoSeeker,
  userId: "seeker-demo-male",
  name: "You (male demo)",
  gender: "Male",
  lookingFor: {
    ...demoSeeker.lookingFor,
    gender_preference: "Female",
  },
};

/** Female seeker demo — use `/match/seeker?demo=female-layla` to see Layla Khaleej (~90% match). */
export const demoFemaleLaylaSeeker: RoommateProfile = {
  ...demoSeeker,
  userId: "seeker-demo-female-layla",
  name: "You (female demo)",
  gender: "Female",
  lookingFor: {
    ...demoSeeker.lookingFor,
    gender_preference: "Female",
  },
};

export function getGuestSeekerBase(): RoommateProfile {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    if (params.get("demo") === "male-seeker") {
      return demoMaleSeeker;
    }
    if (params.get("demo") === "female-layla") {
      return demoFemaleLaylaSeeker;
    }
  }
  return demoSeeker;
}
