import type { JobApplicationQuestionTemplate } from "@/types/jobApplication";

/** Bundled templates — kept in sync with backend/config/job_application_questions.php */
export const JOB_APPLICATION_QUESTION_TEMPLATES: JobApplicationQuestionTemplate[] = [
  {
    id: "interview_availability",
    label: "Choose suitable dates for interview",
    help_text: "Select all dates or windows when you are available for an interview.",
    type: "multi_choice",
    options: [
      "Within 3 days",
      "This week",
      "Next week",
      "Weekends only",
      "Evenings only",
      "Flexible — contact me",
    ],
    default_required: true,
    source: "indeed",
    category: "scheduling",
  },
  {
    id: "years_experience",
    label: "How many years of relevant experience do you have?",
    help_text: "Confirm the total years of experience related to this role.",
    type: "single_choice",
    options: [
      "Less than 1 year",
      "1–2 years",
      "3–5 years",
      "6–8 years",
      "9–12 years",
      "13+ years",
    ],
    default_required: true,
    source: "indeed",
    category: "experience",
  },
  {
    id: "visa_status",
    label: "What is your current UAE visa status?",
    help_text: "Employers use this to assess transfer or sponsorship requirements.",
    type: "single_choice",
    options: [
      "UAE National — no visa required",
      "Employment visa (transferable / NOC available)",
      "Employment visa (not transferable)",
      "Visit / tourist visa",
      "Freelance / remote work permit",
      "Golden Visa",
      "Student visa",
      "Dependent visa",
      "Outside UAE — require sponsorship",
    ],
    default_required: true,
    source: "linkedin",
    category: "eligibility",
  },
  {
    id: "driving_license",
    label: "Do you hold a valid driving licence?",
    help_text: "Indicate UAE or home-country licence status if relevant to the role.",
    type: "single_choice",
    options: [
      "Yes — valid UAE licence",
      "Yes — home country licence only",
      "No",
      "Prefer not to say",
    ],
    default_required: false,
    source: "indeed",
    category: "eligibility",
  },
  {
    id: "notice_period",
    label: "What is your notice period?",
    type: "single_choice",
    options: ["Immediately available", "2 weeks", "1 month", "2 months", "3+ months"],
    default_required: false,
    source: "indeed",
    category: "availability",
  },
  {
    id: "expected_salary",
    label: "What is your expected monthly salary (AED)?",
    type: "text",
    placeholder: "e.g. 18,000 AED",
    default_required: false,
    source: "bayt",
    category: "compensation",
  },
  {
    id: "work_authorization",
    label: "Are you legally authorised to work in the UAE?",
    type: "single_choice",
    options: ["Yes", "No", "Will require visa sponsorship"],
    default_required: true,
    source: "linkedin",
    category: "eligibility",
  },
  {
    id: "education_level",
    label: "Highest level of education completed",
    type: "single_choice",
    options: [
      "High school",
      "Diploma",
      "Bachelor's degree",
      "Master's degree",
      "Doctorate",
      "Professional certification",
    ],
    default_required: false,
    source: "indeed",
    category: "qualifications",
  },
  {
    id: "languages_spoken",
    label: "Languages you speak fluently",
    type: "multi_choice",
    options: ["English", "Arabic", "Hindi", "Urdu", "Tagalog", "French", "Other"],
    default_required: false,
    source: "indeed",
    category: "qualifications",
  },
  {
    id: "willing_to_relocate",
    label: "Are you willing to relocate within the UAE for this role?",
    type: "single_choice",
    options: ["Yes", "No", "Depends on relocation support"],
    default_required: false,
    source: "linkedin",
    category: "availability",
  },
  {
    id: "preferred_start_date",
    label: "When can you start?",
    type: "date",
    default_required: false,
    source: "indeed",
    category: "availability",
  },
  {
    id: "linkedin_profile",
    label: "LinkedIn profile URL",
    type: "text",
    placeholder: "https://linkedin.com/in/…",
    default_required: false,
    source: "linkedin",
    category: "profile",
  },
];

export function templateToJobQuestion(
  template: JobApplicationQuestionTemplate,
  required?: boolean
): import("@/types/jobApplication").JobApplicationQuestion {
  return {
    template_id: template.id,
    label: template.label,
    type: template.type,
    required: required ?? template.default_required,
    options: template.options,
    help_text: template.help_text,
    placeholder: template.placeholder,
    source: template.source,
  };
}
