import { computeCompanyOverallRating } from "@/lib/companyReviews/dimensions";
import type { CompanyReview } from "@/types/companyReviews";

const SEED_REVIEWS: Record<string, CompanyReview[]> = {
  "employer-careem": [
    {
      id: "seed-careem-1",
      employerId: "employer-careem",
      companyName: "Careem",
      reviewerUserId: "seed-careem-1",
      authorLabel: "Former employee · Product Designer · Dubai",
      employmentStatus: "former",
      jobTitle: "Product Designer",
      emirate: "Dubai",
      createdAt: "2026-04-12T09:00:00Z",
      body: "Strong design culture and mentorship from senior ICs. Compensation was competitive for Dubai tech. Workload can spike before major launches, but managers generally protect weekends. Interview process was structured — portfolio review, case study, and team fit.",
      scores: {
        culture: 4,
        compensation: 4,
        work_life: 3,
        career: 5,
        management: 4,
        hiring: 4,
      },
      overallRating: computeCompanyOverallRating({
        culture: 4,
        compensation: 4,
        work_life: 3,
        career: 5,
        management: 4,
        hiring: 4,
      }),
      isSeed: true,
    },
    {
      id: "seed-careem-2",
      employerId: "employer-careem",
      companyName: "Careem",
      reviewerUserId: "seed-careem-2",
      authorLabel: "Interview experience · Engineering Manager · Dubai",
      employmentStatus: "applicant",
      jobTitle: "Engineering Manager",
      emirate: "Dubai",
      createdAt: "2026-03-28T14:30:00Z",
      body: "Recruiter was responsive and salary range was shared early. Three rounds over two weeks — reasonable for a senior hire. Questions focused on leadership and delivery, not trivia. Did not receive detailed feedback after rejection, which was the only downside.",
      scores: {
        culture: 4,
        compensation: 4,
        work_life: 4,
        career: 4,
        management: 4,
        hiring: 3,
      },
      overallRating: computeCompanyOverallRating({
        culture: 4,
        compensation: 4,
        work_life: 4,
        career: 4,
        management: 4,
        hiring: 3,
      }),
      isSeed: true,
    },
  ],
  "employer-property-finder": [
    {
      id: "seed-pf-1",
      employerId: "employer-property-finder",
      companyName: "Property Finder",
      reviewerUserId: "seed-pf-1",
      authorLabel: "Current employee · Software Engineer · Dubai",
      employmentStatus: "current",
      jobTitle: "Software Engineer",
      emirate: "Dubai",
      createdAt: "2026-05-01T11:00:00Z",
      body: "Good balance of autonomy and support. Benefits include medical for dependents and annual bonus. Hybrid policy is genuinely flexible. Would like clearer promotion criteria, but overall a solid PropTech employer in Dubai.",
      scores: {
        culture: 4,
        compensation: 4,
        work_life: 4,
        career: 3,
        management: 4,
        hiring: 4,
      },
      overallRating: computeCompanyOverallRating({
        culture: 4,
        compensation: 4,
        work_life: 4,
        career: 3,
        management: 4,
        hiring: 4,
      }),
      isSeed: true,
    },
  ],
  "employer-talabat": [
    {
      id: "seed-talabat-1",
      employerId: "employer-talabat",
      companyName: "Talabat",
      reviewerUserId: "seed-talabat-1",
      authorLabel: "Former employee · Operations Lead · Dubai",
      employmentStatus: "former",
      jobTitle: "Operations Lead",
      emirate: "Dubai",
      createdAt: "2026-02-18T08:45:00Z",
      body: "High-energy environment — you learn quickly but expect long hours during peak campaigns. Pay was fair with performance bonuses. Leadership is direct and data-driven. Good stepping stone if you want ops experience at scale.",
      scores: {
        culture: 3,
        compensation: 4,
        work_life: 2,
        career: 4,
        management: 3,
        hiring: 4,
      },
      overallRating: computeCompanyOverallRating({
        culture: 3,
        compensation: 4,
        work_life: 2,
        career: 4,
        management: 3,
        hiring: 4,
      }),
      isSeed: true,
    },
    {
      id: "seed-talabat-2",
      employerId: "employer-talabat",
      companyName: "Talabat",
      reviewerUserId: "seed-talabat-2",
      authorLabel: "Interview experience · Marketing Specialist · Dubai",
      employmentStatus: "applicant",
      jobTitle: "Marketing Specialist",
      emirate: "Dubai",
      createdAt: "2026-04-05T16:00:00Z",
      body: "Applied through the careers page. HR screen was professional; hiring manager asked relevant campaign examples. Timeline stretched to four weeks without updates — typical for larger teams but worth noting.",
      scores: {
        culture: 3,
        compensation: 3,
        work_life: 3,
        career: 3,
        management: 4,
        hiring: 3,
      },
      overallRating: computeCompanyOverallRating({
        culture: 3,
        compensation: 3,
        work_life: 3,
        career: 3,
        management: 4,
        hiring: 3,
      }),
      isSeed: true,
    },
  ],
  "employer-tarjama": [
    {
      id: "seed-tarjama-1",
      employerId: "employer-tarjama",
      companyName: "Tarjama",
      reviewerUserId: "seed-tarjama-1",
      authorLabel: "Current employee · Linguist · Abu Dhabi",
      employmentStatus: "current",
      jobTitle: "Linguist",
      emirate: "Abu Dhabi",
      createdAt: "2026-04-22T10:15:00Z",
      body: "Specialist-friendly employer with meaningful Arabic NLP work. Smaller team means visibility to leadership. Compensation is modest vs big tech but hours are reasonable and remote days are respected.",
      scores: {
        culture: 5,
        compensation: 3,
        work_life: 5,
        career: 4,
        management: 5,
        hiring: 4,
      },
      overallRating: computeCompanyOverallRating({
        culture: 5,
        compensation: 3,
        work_life: 5,
        career: 4,
        management: 5,
        hiring: 4,
      }),
      isSeed: true,
    },
  ],
  "employer-tabby": [
    {
      id: "seed-tabby-1",
      employerId: "employer-tabby",
      companyName: "Tabby",
      reviewerUserId: "seed-tabby-1",
      authorLabel: "Former employee · Data Analyst · Dubai",
      employmentStatus: "former",
      jobTitle: "Data Analyst",
      emirate: "Dubai",
      createdAt: "2026-03-10T13:20:00Z",
      body: "Transparent leveling and equity discussions during offer stage. Fast-paced fintech with smart peers. Work-life balance depends on squad — mine was manageable. Interview loop included a take-home case that reflected real work.",
      scores: {
        culture: 4,
        compensation: 5,
        work_life: 3,
        career: 4,
        management: 4,
        hiring: 5,
      },
      overallRating: computeCompanyOverallRating({
        culture: 4,
        compensation: 5,
        work_life: 3,
        career: 4,
        management: 4,
        hiring: 5,
      }),
      isSeed: true,
    },
  ],
};

export function getSeedCompanyReviews(employerId: string): CompanyReview[] {
  return SEED_REVIEWS[employerId] ?? [];
}
